version: '3.8'

services:
  img-endpoint:
    build: .
    container_name: img_endpoint_service
    restart: unless-stopped
    expose:
      - 8000  # Don't publish the port externally, only for internal communication
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    networks:
      - sovereign_default  # Connect to the same network as the main project

networks:
  sovereign_default:
    external: true  # Use the existing network